name: smart_proxy_app
services:
  server:
    container_name: web_api
    image: web_api_image
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports: 
      - "8080:8080"
    depends_on: 
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=TestMongoDB
      - MONGO_LOG_LEVEL=warning
volumes:
  mongo_data:
  mongo_config:
      