# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: broker.proto for package 'Broker.Proto'

require 'grpc'
require 'broker_pb'

module Broker
  module Proto
    module Broker
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'broker.v1.Broker'

        rpc :Publish, ::Broker::Proto::Envelope, ::Broker::Proto::PublishAck
        rpc :Subscribe, ::Broker::Proto::Subscription, stream(::Broker::Proto::Envelope)
        rpc :Ack, ::Broker::Proto::AckRequest, ::Broker::Proto::AckReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
