# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broker.proto

require 'google/protobuf'

descriptor_data = "\n\x0c\x62roker.proto\x12\tbroker.v1\"\xb9\x01\n\x08\x45nvelope\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x31\n\x07headers\x18\x03 \x03(\x0b\x32 .broker.v1.Envelope.HeadersEntry\x12\x12\n\nmessage_id\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"B\n\nPublishAck\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\x1f\n\x0cSubscription\x12\x0f\n\x07subject\x18\x01 \x01(\t\"1\n\nAckRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\" \n\x08\x41\x63kReply\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xaf\x01\n\x06\x42roker\x12\x35\n\x07Publish\x12\x13.broker.v1.Envelope\x1a\x15.broker.v1.PublishAck\x12;\n\tSubscribe\x12\x17.broker.v1.Subscription\x1a\x13.broker.v1.Envelope0\x01\x12\x31\n\x03\x41\x63k\x12\x15.broker.v1.AckRequest\x1a\x13.broker.v1.AckReplyB\x10\xea\x02\rBroker::Protob\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Broker
  module Proto
    Envelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('broker.v1.Envelope').msgclass
    PublishAck = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('broker.v1.PublishAck').msgclass
    Subscription = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('broker.v1.Subscription').msgclass
    AckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('broker.v1.AckRequest').msgclass
    AckReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('broker.v1.AckReply').msgclass
  end
end
